"""Typed failures for the Local Computing trust boundary."""

from enum import Enum


class LocalComputingError(str, Enum):
    """Failure categories that must never be interpreted as authorization."""

    MALFORMED_REQUEST = "MALFORMED_REQUEST"
    UNKNOWN_PRINCIPAL = "UNKNOWN_PRINCIPAL"
    INVALID_TRUST_STATE = "INVALID_TRUST_STATE"
    UNSUPPORTED_CAPABILITY = "UNSUPPORTED_CAPABILITY"
    PLATFORM_UNAVAILABLE = "PLATFORM_UNAVAILABLE"
    PLATFORM_INTEGRATION_FAILURE = "PLATFORM_INTEGRATION_FAILURE"
    ENFORCEMENT_FAILURE = "ENFORCEMENT_FAILURE"
    AUDIT_FAILURE = "AUDIT_FAILURE"
    INVALID_TARGET = "INVALID_TARGET"
    PARTIAL_EXECUTION = "PARTIAL_EXECUTION"
    UNEXPECTED_RESULT = "UNEXPECTED_RESULT"
